import type { EnvRequest } from '../../types/generation-plan.js';

export interface EnvMergeResult {
  readonly contents: string;
  /** Keys appended to the file. */
  readonly added: readonly string[];
  /** Keys the file already defined, left exactly as they were. */
  readonly skipped: readonly string[];
}

/**
 * Written in place of any value marked `secret`.
 *
 * Atlas will not put a usable secret in a file, even a good one. `.env` files get committed by
 * accident and `.env.example` gets committed on purpose, so a generated key would ship to
 * production looking deliberate — and every project generated by the same Atlas version would
 * share it. An obviously fake value fails loudly at startup instead, which is the outcome we
 * want.
 */
export const SECRET_PLACEHOLDER = 'replace-me';

/** The note written above every placeholder, so nobody mistakes one for a real value. */
const SECRET_NOTICE = '# atlas: placeholder — replace this before running the app';

/**
 * Assignment lines, including the `export KEY=value` form some projects use.
 *
 * Only the key is captured: the value is never parsed, because Atlas never needs to read one
 * and quoting rules differ between dotenv implementations.
 */
const ASSIGNMENT = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=/u;

const TRAILING_NEWLINE = /\r?\n$/u;

const TRAILING_BLANK_LINE = /(?:\r?\n){2}$/u;

function existingKeys(source: string): Set<string> {
  const keys = new Set<string>();

  for (const line of source.split(/\r?\n/u)) {
    const key = ASSIGNMENT.exec(line)?.[1];
    if (key !== undefined) keys.add(key);
  }

  return keys;
}

/**
 * Appends environment variables to a `.env` or `.env.example` file.
 *
 * Append-only, and an existing key is never re-valued: the local `.env` holds the credentials
 * that make the user's machine work, and overwriting one would break their setup in a way
 * that is tedious to trace back to a code generator.
 */
export function mergeEnvFile(
  existing: string | undefined,
  requests: readonly EnvRequest[],
): EnvMergeResult {
  const source = existing ?? '';
  const eol = source.includes('\r\n') ? '\r\n' : '\n';
  const present = existingKeys(source);

  const added: string[] = [];
  const skipped: string[] = [];
  const appended: string[] = [];

  for (const request of requests) {
    if (present.has(request.key)) {
      skipped.push(request.key);
      continue;
    }

    // Guards against a plan that lists the same key twice; the first one wins.
    present.add(request.key);

    const heading: string[] = [];
    if (request.comment !== undefined) heading.push(`# ${request.comment}`);
    if (request.secret) heading.push(SECRET_NOTICE);

    // A commented entry gets one blank line of separation so its comment cannot be misread as
    // belonging to the assignment above it. Bare entries get none — a run that adds three
    // variables should read as a block, not a list with gaps.
    if (heading.length > 0 && appended.length > 0) appended.push('');
    appended.push(...heading);
    appended.push(`${request.key}=${request.secret ? SECRET_PLACEHOLDER : request.value}`);
    added.push(request.key);
  }

  if (appended.length === 0) return { contents: source, added, skipped };

  // Terminate the existing content, then separate the new block with a single blank line —
  // unless the file already ends with one, since stacking a second is exactly the blank-line
  // churn that makes a one-variable addition look like a reformat.
  const terminated =
    source.length === 0 || TRAILING_NEWLINE.test(source) ? source : `${source}${eol}`;
  const needsBlank = terminated.length > 0 && !TRAILING_BLANK_LINE.test(terminated);

  return {
    contents: `${terminated}${needsBlank ? eol : ''}${appended.join(eol)}${eol}`,
    added,
    skipped,
  };
}
